Feature/ikm 20240919 hybrid reasoner
ikmdev/tinkar-core pull request #44
Opened 2024-10-07 17:18 UTC by emays

2024-10-08 15:34 UTC, carldea requested changes
@emays 
I have some comments and questions in the code review.

2024-10-09 16:58 UTC, emays commented
The tests and especially the ITs are still a work in progress pending resolution of data issues. So some of that code that's commented out will be reviewed and potentially reinstated when the data issues are resolved.

2024-10-10 17:09 UTC, stenkarl approved these changes

2024-10-10 23:45 UTC, rbradley813 commented on reasoner/reasoner-elk-snomed/src/test/java/dev/ikm/tinkar/reasoner/elksnomed/SnomedUS20230901ElkSnomedClassifierTestIT.java
>  //			OWLOntology oo = ontology.getOntology();
@emays said he will refactor the tests once the new data is provided

2024-10-11 12:55 UTC, carldea approved these changes
looks good to me.

2024-10-11 13:14 UTC, merged